### ISSUE TITLE
iOS Recording Not Completing

### ISSUE THREAD

**Issue by FlammableFork** [NateRickard/Plugin.AudioRecorder#2]
First, thank you for making this great plugin.  However, I am having an issue with iOS (UWP and Android are unaffected).

Almost every other time I execute StartRecording (the frequency is actually intermittent), the recording doesn't complete automatically.  I have tried both the Task and event-driven approaches.  When I manually stop recording by calling StopRecording, the result is always null in these instances.

As a rundown of the process that I can see:

* StartRecording is called
* IsRecording changes to true
* StopRecordingOnSilence has no effect (Task is not completed/AudioInputReceived does not fire)
* StopRecordingAfterTimeout has no effect (Task is not completed/AudioInputReceived does not fire)
* StopRecording is called
* IsRecording changes to false
* Task is completed/AudioInputReceived fires
* FilePath is null (always)

The next time I execute StartRecording everything might work perfectly, but I will quickly run into another occurrence of the problem.  As a reference, here are the settings I configure on the service:

StopRecordingOnSilence = true,
AudioSilenceTimeout = TimeSpan.FromSeconds(2),
SilenceThreshold = 0.1f,
StopRecordingAfterTimeout = true,
TotalAudioTimeout = TimeSpan.FromSeconds(5),
PreferredSampleRate = 8000

I hope this makes sense.  Thanks.

**Comment by NateRickard** [comment]
@FlammableFork is this in a simulator or on device?  Can you confirm you're on the latest code/NuGet version?  There was a version released a few iterations ago where I saw and fixed a similar issue.

That said, I've not seen this behavior happen since and I did a lot of repeated testing for https://github.com/NateRickard/Xamarin.Cognitive.BingSpeech.  Can you reproduce the issue with the sample app from this repo or the Bing Speech sample app for iOS?  Curious if this is environmental/setup vs. specific to your app.

I've not tested a lot when changing the sample rate & silence threshold, so I'll try to do some testing with your settings as well and see how that affects things.

**Comment by FlammableFork** [comment]
This is on a physical device (iPad 5), and I have confirmed that I am using version 0.8.0, which is the latest on Nuget.

I will see about testing the sample application.  I will also see if things are different with the default sample rate and silence threshold.

**Comment by FlammableFork** [comment]
I am at my wit's end.  I have tried refactoring my code in every way conceivable, but it still has this issue.  I did write a sample application, in which I was unable to reproduce the issue.  This doesn't change the fact that the problem in my main project is awaiting the recording.

I have the following lines:

Task<string> recording = await audioService.StartRecording();
string filePath = await recording;

Execution always makes it to the second line, but it doesn't return automatically every time.  I can go through several very successful attempts, but then, even though nothing has changed, the await doesn't complete.  I can manually call audioService.StopRecording() at which point it will return (always null) and I can then try again.  This is occurring regardless of the configuration of the AudioRecorderService (even leaving it using the defaults).  Unfortunately, I have no visibility into the running code to try and debug, and the only way I can think to proceed would be to try and incorporate your code directly into my project, which isn't very ideal.  Do you have any ideas?

**Comment by NateRickard** [comment]
@FlammableFork I'm still not able to reproduce the issue on my end, either, which makes it pretty hard to debug :(

It's probably a lot easier to pull the code down and debug than you think.  Just need to reference the project output rather than using the NuGet package.  For instance, the way I develop it, I replace the NuGet references in the sample projects with references to the actual platform project it needs (i.e. iOS sample app references the iOS library project).  This would give you full ability to debug into the plugin, and also it will spit out a lot more debug info when compiled and run in a Debug config.

**Comment by FlammableFork** [comment]
Thank you for continuing to look into this.  I will try importing the project into my solution and see what I can figure out.  Thanks.

**Comment by FlammableFork** [comment]
I found the problem.  Apparently iOS is somewhat half-duplex with respect to audio.  If anything is playing at all, recording will not start.  In my app, I was playing an audio notification to the user to indicate that recording had started.  When the request to start recording occurred before the notification had COMPLETELY finished (simple timing), the problem would surface.  Removing the audio notification altogether fixed the issue.  I have since refactored things to ensure that the notification is completely finished playing before I start recording, and everything is working as expected.  Thanks for your help.

It might be a good addition for iOS to check to see if any audio is playing at the time recording was requested, if that is even possible.  That way, there would be some feedback (at least to the developer) and the request wouldn't simply fly off into the ether.

**Comment by NateRickard** [comment]
@FlammableFork good sleuthing... I'm really surprised that doesn't generate an error as it should.  I'm not sure if I can detect audio easily prior to attempting to record, but I will definitely add something in the readme calling this out.  Thanks for digging into it!
