### ISSUE TITLE
Will not be recorded while talking softly

### ISSUE THREAD

**Issue by hashmatamiri** [NateRickard/Plugin.AudioRecorder#34]
Hi 
Unfortunately, it's not working if you try to talk quietly. To record any sound or voice it has to be loud enough to be recorded. 
In general, if you record something and even if you don't say anything, you're still able to hear some background noises. 
But in this case, using (Plugin.AudioRecorder), it's not working. 

Do I only have this problem ???

Thanks

**Comment by NateRickard** [comment]
It's a bit hard to determine your issue from the info you provided:

- If it's auto-stopping the recording due to perceived silence, you can either adjust the silence threshold or turn off that feature altogether and stop the recording manually.

- If the issue is that your device is just not picking up the audio, then it's less clear. This library doesn't do anything to alter the mic input or anything like that, so at some point this is going to be a bit dependent on the device/mic you're working with. I've tried a bunch of different devices in my testing and have had good results with the mics picking up my voice... but that's my intent, of course - I'm not trying to pick up background noise. You may be able to adjust the audio input stream somehow, such as adjusting the iOS audio session, to achieve better results.

**Comment by hashmatamiri** [comment]
You were right Rickard. 

Although in the beginning, I adjusted the silence threshold, somehow it didn't work. 
And then after reading your comment, I adjusted it again, and test it on my other devices, Suprisly everything worked fine.

So the problem was, with one of my devices. 

I appreciate your help.
Thanks a lot.
