### ISSUE TITLE
Hello NateRickard

### ISSUE THREAD

**Issue by MingJiang1988** [NateRickard/Plugin.AudioRecorder#7]
Hello
I am using Plugin.AudioRecoder in visual studio 2017 xamarin project
 My Xamarin project is portable
So when I install your plugin with NewGet, your plugin were installed for android and ios
But your plugin isn't installed for Portable Forms
So I got follow issue

Error		Could not install package 'Plugin.AudioRecorder 0.8.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

How can i use  your plugin in my project
Please help me
Best Regards

**Comment by NateRickard** [comment]
@MingJiang1988 The default PCL profile for a new Xamarin.Forms project should be Profile111 - I've just reverified this by creating a new Forms project with the latest project template.

You need to adjust your Forms PCL project to use PCL Profile111 in order to use the plugin directly in your Profile259 PCL.  You could also clone this repo and change the profile to 259 and recompile a dll that will work for your scenario.
